build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths:
    - ".docker/"
    - "docs/"
    - "example/"
    - "tests/"
  dependency_paths:
    - "vendor/"

checks:
  php: true
tools:
  php_cs_fixer: true
  external_code_coverage:
    runs: 3
    timeout: 2100 # Timeout in seconds.