language: php

php:
  - 7.4
  - 8.0

env:
  global:
    - XDEBUG_MODE=coverage

before_install:
  - travis_retry composer self-update && composer --version

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --no-interaction --prefer-dist

script:
  - ./vendor/bin/php-cs-fixer fix --verbose --show-progress=dots --dry-run --config=.php_cs.php
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover